spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fabric_international?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456